// =============================================
//  WAVELY — HTTPS Local Server
//  Run: node server.js
// =============================================

const https = require('https');
const fs = require('fs');
const path = require('path');

const PORT = 3000;

// MIME types
const MIME = {
  '.html': 'text/html',
  '.css':  'text/css',
  '.js':   'application/javascript',
  '.json': 'application/json',
  '.png':  'image/png',
  '.jpg':  'image/jpeg',
  '.ico':  'image/x-icon',
};

// SSL certs generated by mkcert
// const options = {
//   cert: fs.readFileSync(path.join(__dirname, 'localhost.pem')),
//   key:  fs.readFileSync(path.join(__dirname, 'localhost-key.pem')),
// };

// const server = https.createServer(options, (req, res) => {

  const http = require('http');

const server = http.createServer((req, res) => {
  // All routes serve index.html (for SPA callback handling)
  let filePath = req.url === '/' || req.url.startsWith('/callback')
    ? '/index.html'
    : req.url.split('?')[0]; // strip query params

  const fullPath = path.join(__dirname, filePath);
  const ext = path.extname(fullPath);
  const contentType = MIME[ext] || 'text/plain';

  fs.readFile(fullPath, (err, data) => {
    if (err) {
      // Fallback to index.html for any missing route
      fs.readFile(path.join(__dirname, 'index.html'), (err2, data2) => {
        if (err2) {
          res.writeHead(404);
          res.end('Not found');
        } else {
          res.writeHead(200, { 'Content-Type': 'text/html' });
          res.end(data2);
        }
      });
    } else {
      res.writeHead(200, { 'Content-Type': contentType });
      res.end(data);
    }
  });
});

server.listen(PORT, () => {
  console.log(`\n🎵 Wavely is running!`);
  console.log(`👉 Open: http://localhost:${PORT}\n`);
});
